pipeline
{
     agent any
     environment{
          SERVER_CREDENTIALS =credentials('server_credentials')
     }
    stages{
    
            stage('build')
            {
            steps
               {
               echo 'this is build step' 
                }
            }
            stage('test')
            {
            steps
               {
               echo 'this is test step' 
                }
            }
            stage('deploy')
            {
            steps
               {
               echo 'this is deploy step' 
                    withCredentials{[
                         usernamePassword(credentials :'server_credentials', usernameVariable: USER, passwordVariable: PWD )
                    ]}
                    {
                    sh "username: $(USER)"
                         "password: $(PWD)"
                    }
                }
            }
          }
    
}
